#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "android" {

	set root=(hd1,2)
	linux /android-4.30-test/kernel quiet root=/dev/ram0 androidboot.hardware=eeepc acpi_sleep=s3_bios,s3mode SRC=/android-4.3-test
	initrd /android-4.3-test/initrd.img



}


